import Head from 'next/head'
import Image from "next/image"
import cmc from "../public/images/cmc.png"
import cc from "../public/images/cc.png"
import cm from "../public/images/cm.png"
import GetInvolved from '../components/getinvolved'


export default function Contact() {


    return(
        <div className="contact_bg  min-h-1/5 pt-[120px] md:pt-[180px]">
            <Head>
            <title>Dreams&Degrees</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="preload" as="image" href="https://res.cloudinary.com/dimejiscloud/image/upload/q_auto:best/v1652026702/dd/aboutline_vgyj9u.png" />
            <link rel="icon" href="/images/logo.png" />
            </Head>

            <div className='text-center font-fellix md:px-0 px-7'>
            <small className='text-bk text-14 font-[700] uppercase -tracking-[0.36px]'>Contact Us</small>
            <div className='text-bk text-48  font-[700] leading-[56px] mt-[40px] mb-[80px] -tracking-[2px]'> Get in Touch with us by filling the <br /> form below</div>
            <div className='contact_form mb-[146px]'>
                <form method="POST"  action="http://eepurl.com/h2pb8b">
                    <label className='mb-[30px] block mx-auto'>
                        <input type='text' name="name" placeholder='Your name' className='p-[15px]  bg-fm rounded-[28px]' />
                    </label>
                    <label className='mb-[30px] block  mx-auto '>
                        <input type='text' name="email"  placeholder='Your email' className='p-[15px] bg-fm rounded-[28px]' />
                    </label>
                    <label className='mb-[30px] block mx-auto'>
                        <input type='text' name="phone number"  placeholder='Your phone number' className='p-[15px] bg-fm rounded-[28px]' />
                    </label>
                    <label className='mb-[30px] block mx-auto'>
                        <textarea type='text' name="message"  placeholder='Your message' className='textarea h-[240px] p-[15px] bg-fm rounded-[28px]' ></textarea>
                    </label>
                    <button className="contact_btn rounded-[28px] bg-pry text-[#ffff] text-16 font-[700]  py-[15px]">Send a Message</button>
                </form>
            </div>
            <div className="xl:w-[900px] xl:container md:w-[700px]  mx-auto xl:px-[20px] flex justify-between flex-col md:flex-row">
                <div className='flex flex-col items-center '>
                    <div className='relative w-[40px] h-[40px] '> 
                        <Image src={cm} alt="cm" layout='fill' quality={100}   />
                    </div>
                    <p className='text-18 mt-[31px] mb-[8px] text-bk block font-[700]'>Send a mail</p>
                    <p className='block text-[#594D6D] text-18 font-[400]'>hello@dreamsanddegrees.com</p>
                </div>
                <div className='flex flex-col items-center mt-[76px] mb-[68px] md:mt-0 md:mb-0'>
                    <div className='relative w-[40px] h-[40px] '> 
                        <Image src={cc} alt="cc" layout='fill' quality={100}   />
                    </div>
                    <p className='text-18 mt-[31px] mb-[8px] text-bk block font-[700]'>Call us</p>
                    <p className='block text-[#594D6D] text-18 font-[400]'>+61473839657</p>
                </div>
                <div className='flex flex-col items-center'>
                    <div className='relative w-[40px] h-[40px] '> 
                        <Image src={cmc} alt="cmc" layout='fill' quality={100} />
                    </div>
                    <p className='text-18 mt-[31px] mb-[8px] text-bk block font-[700]'>Follow us on Twitter and Instagram</p>
                    <p className='block text-[#594D6D] text-18 font-[400]'>@dreamsandegrees</p>
                </div>
            </div>
            </div>
            <div className='mt-[188px] mb-[100px]'>
                <GetInvolved />
            </div>
        </div>
    )

}