import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div className='header_container img_box min-h-1/6'>
      <Head>
        <title>Dreams&Degrees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" as="image" href="/images/gradient.png" />
        <link rel="preload" as="image" href="/images/lines1.png" />
      </Head>

      

  </div>
  )
}
