import Head from 'next/head'
import styled from "styled-components"
import Image from "next/image"
import headergirls from "../public/images/headergirls.png"
import WhoWeAre from '../components/whoarewe'
import Impact from '../components/impact'
import Programs from "../components/program"
import Membership from '../components/membership'




const Button = styled.button`
    background: ${props => props.primary ? "#D68676" : props.notprimary ? "transparent" : ""};
    color: ${props => props.primary ? "white" 
    : props.notprimary ? "#12022F" : "black" };

    font-size: 1em;
    padding: 15px 59px;
    border: ${props => props.primary ? "" : 
        props.notprimary ? "" : "2px solid #1A202C"  };
    border-radius: 28px;
    font-weight:600;
`

export default function Home() {
  return (
    <div>
      <header className='header_container img_box min-h-1/6 flex items-end flex-col justify-end relative mb-[102px] md:mb-0'>
      <Head>
        <title>Dreams&Degrees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./images/logo.png" />
        <link rel="preload" as="image" href="/images/gradient.png" imagesrcset="/images/gradient_sm.png 540w,  /images/gradient.png 1500w" />
        <link rel="preload" as="image" href="/images/lines1.png" />
      </Head>

      <article className='header_main md:container mx-auto  md:px-10 pt-5 text-center mt-[120px]'>
        <h1 className='text-42 px-[25px] md:px-0 md:text-56 leading-[63px] font-bold font-["paytone-one"] text-bk'>A Digital <span className="text-pry">Sisterhood</span> for<br/>Ambitious females</h1>
        <p className="text-para px-[20px] md:px-0 mt-[24px] mb-[16px] mb-[40px] md:mb-0 md:mt-0 " >We exist to connect, educate and empower females.</p>
        <div className='header_btn_div mt-[40px] px-[20px] md:px-0'>
          <Button className="mr-4 md:mb-0 mb-[8.9px]" primary>Join Community</Button>
          <Button >Get Involved</Button>
        </div>
        <div className='w-[100%] h-[206px] md:w-[768px] md:h-[395px] mt-[80px] mx-auto relative'>
          <Image src={headergirls} alt="headergirls"  layout="fill" quality={100}  priority />
        </div>
      </article>
    </header>
      <main className="mainbg">
        <WhoWeAre />
        <Impact />
        <Membership />
        <Programs />
      </main>
    </div>
  )
}
